FOOD_MAPPING = {
    "apple_pie": ["apple pie", "pie, apple", "traditional apple pie"],
    "baby_back_ribs": ["pork ribs", "baby back ribs", "barbecue ribs", "bbq ribs"],
    "baklava": ["baklava", "turkish baklava", "phyllo pastry with nuts"],
    "beef_carpaccio": ["beef carpaccio", "raw beef carpaccio", "sliced raw beef"],
    "beef_tartare": ["beef tartare", "steak tartare", "raw beef tartare"],
    "beet_salad": ["beet salad", "beetroot salad", "roasted beet salad"],
    "beignets": ["beignets", "french doughnuts", "powdered sugar doughnuts"],
    "bibimbap": ["bibimbap", "korean bibimbap", "mixed rice bowl"],
    "bread_pudding": ["bread pudding", "traditional bread pudding"],
    "breakfast_burrito": ["breakfast burrito", "egg burrito", "morning burrito"],
    "bruschetta": ["bruschetta", "tomato bruschetta", "italian bruschetta"],
    "caesar_salad": ["caesar salad", "chicken caesar salad"],
    "cannoli": ["cannoli", "italian cannoli", "sicilian cannoli"],
    "caprese_salad": ["caprese salad", "tomato mozzarella salad"],
    "carrot_cake": ["carrot cake", "spiced carrot cake"],
    "ceviche": ["ceviche", "seafood ceviche", "fish ceviche"],
    "cheesecake": ["cheesecake", "new york cheesecake", "plain cheesecake"],
    "cheese_plate": ["cheese plate", "cheese board", "assorted cheese"],
    "chicken_curry": ["chicken curry", "curry chicken", "indian chicken curry"],
    "chicken_quesadilla": ["chicken quesadilla", "cheese quesadilla with chicken"],
    "fried_chicken": ["chicken wings", "buffalo wings", "fried chicken wings"],
    "chocolate_cake": ["chocolate cake", "dark chocolate cake"],
    "chocolate_mousse": ["chocolate mousse", "dark chocolate mousse"],
    "churros": ["churros", "spanish churros", "fried churros"],
    "clam_chowder": ["clam chowder", "new england clam chowder"],
    "club_sandwich": ["club sandwich", "triple decker sandwich"],
    "crab_cakes": ["crab cakes", "maryland crab cakes"],
    "creme_brulee": ["creme brulee", "french custard", "burnt cream"],
    "croque_madame": ["croque madame", "french sandwich with egg"],
    "cup_cakes": ["cupcakes", "vanilla cupcakes", "chocolate cupcakes"],
    "deviled_eggs": ["deviled eggs", "stuffed eggs"],
    "donuts": ["donuts", "doughnuts", "glazed donuts"],
    "dumplings": ["dumplings", "asian dumplings", "potstickers"],
    "edamame": ["edamame", "soybeans", "steamed edamame"],
    "eggs_benedict": ["eggs benedict", "poached eggs with hollandaise"],
    "escargots": ["escargots", "french snails", "garlic snails"],
    "falafel": ["falafel", "chickpea falafel", "middle eastern falafel"],
    "filet_mignon": ["filet mignon", "beef tenderloin", "beef fillet"],
    "fish_and_chips": ["fish and chips", "fried fish with fries"],
    "foie_gras": ["foie gras", "duck liver", "goose liver"],
    "french_fries": ["french fries", "fried potatoes", "potato fries"],
    "french_onion_soup": ["french onion soup", "onion soup"],
    "french_toast": ["french toast", "pain perdu", "eggy bread"],
    "fried_calamari": ["fried calamari", "calamari", "squid rings"],
    "fried_rice": ["fried rice", "chinese fried rice", "asian fried rice"],
    "frozen_yogurt": ["frozen yogurt", "froyo", "yogurt ice cream"],
    "garlic_bread": ["garlic bread", "toasted garlic bread"],
    "gnocchi": ["gnocchi", "potato gnocchi", "italian gnocchi"],
    "greek_salad": ["greek salad", "mediterranean salad"],
    "grilled_cheese_sandwich": ["grilled cheese", "cheese sandwich"],
    "grilled_salmon": ["grilled salmon", "salmon fillet", "cooked salmon"],
    "guacamole": ["guacamole", "avocado dip"],
    "gyoza": ["gyoza", "japanese dumplings", "potstickers"],
    "hamburger": ["hamburger", "beef burger", "cheeseburger"],
    "hot_and_sour_soup": ["hot and sour soup", "chinese soup"],
    "hot_dog": ["hot dog", "frankfurter", "wiener"],
    "huevos_rancheros": ["huevos rancheros", "mexican eggs"],
    "hummus": ["hummus", "chickpea dip", "hummus dip"],
    "ice_cream": ["ice cream", "vanilla ice cream", "chocolate ice cream"],
    "lasagna": ["lasagna", "pasta lasagna", "meat lasagna"],
    "lobster_bisque": ["lobster bisque", "cream of lobster soup"],
    "lobster_roll_sandwich": ["lobster roll", "maine lobster roll"],
    "macaroni_and_cheese": ["macaroni and cheese", "mac and cheese"],
    "macarons": ["macarons", "french macarons", "almond macarons"],
    "miso_soup": ["miso soup", "japanese soup"],
    "mussels": ["mussels", "steamed mussels", "cooked mussels"],
    "nachos": ["nachos", "tortilla chips with cheese"],
    "omelette": ["omelette", "egg omelette", "cheese omelette"],
    "onion_rings": ["onion rings", "fried onion rings"],
    "oysters": ["oysters", "raw oysters", "fresh oysters"],
    "pad_thai": ["pad thai", "thai noodles"],
    "paella": ["paella", "spanish paella", "seafood paella"],
    "pancakes": ["pancakes", "breakfast pancakes"],
    "panna_cotta": ["panna cotta", "italian cream dessert"],
    "peking_duck": ["peking duck", "chinese roast duck"],
    "pho": ["pho", "vietnamese soup", "beef noodle soup"],
    "pizza": ["pizza", "cheese pizza", "pepperoni pizza"],
    "pork_chop": ["pork chop", "grilled pork chop"],
    "poutine": ["poutine", "canadian poutine", "gravy and cheese fries"],
    "prime_rib": ["prime rib", "standing rib roast"],
    "pulled_pork_sandwich": ["pulled pork sandwich", "bbq pulled pork"],
    "ramen": ["ramen", "japanese ramen", "noodle soup"],
    "ravioli": ["ravioli", "cheese ravioli", "meat ravioli"],
    "red_velvet_cake": ["red velvet cake", "red cake"],
    "risotto": ["risotto", "mushroom risotto", "italian rice"],
    "samosa": ["samosa", "indian samosa", "vegetable samosa"],
    "sashimi": ["sashimi", "raw fish", "japanese sashimi"],
    "scallops": ["scallops", "sea scallops", "pan seared scallops"],
    "seaweed_salad": ["seaweed salad", "japanese seaweed salad"],
    "shrimp_and_grits": ["shrimp and grits", "southern shrimp and grits"],
    "spaghetti_bolognese": ["spaghetti bolognese", "meat sauce pasta"],
    "spaghetti_carbonara": ["spaghetti carbonara", "carbonara pasta"],
    "spring_rolls": ["spring rolls", "egg rolls", "vietnamese spring rolls"],
    "steak": ["steak", "beef steak", "grilled steak"],
    "strawberry_shortcake": ["strawberry shortcake", "fruit shortcake"],
    "sushi": ["sushi", "sushi rolls", "japanese sushi"],
    "tacos": ["tacos", "mexican tacos", "beef tacos"],
    "takoyaki": ["takoyaki", "octopus balls", "japanese takoyaki"],
    "tiramisu": ["tiramisu", "coffee tiramisu", "italian tiramisu"],
    "tuna_tartare": ["tuna tartare", "raw tuna", "spiced tuna tartare"],
    "waffles": ["waffles", "belgian waffles", "breakfast waffles"]
}
